import { useState, useMemo } from 'react';
import { ScreenHeader, Legend } from './HelpPanel.jsx';
import { DEFENSE_CYCLE, ATTACK, fmt } from '../terminology.js';
import { OBJECTIVES, STAGES } from '../controlModel.js';
import { generateActions, addCumulativeReduction } from '../effortModel.js';
import { aggregateRisk, computeRiskFromPerformance } from '../performanceModel.js';
import { DATA } from '../data.js';

const P = DEFENSE_CYCLE.phases;
const STAGE_COLORS = {
  "Initial Access": { bg: '#E6F1FB', text: '#0C447C', dot: '#378ADD' },
  "Transit":        { bg: '#FAEEDA', text: '#633806', dot: '#BA7517' },
  "Payoff":         { bg: '#FCEBEB', text: '#791F1F', dot: '#E24B4A' },
};

export default function ActionQueue({ onNavigate, onThemeClick, userThemes = [] }) {
  const [budgetDays, setBudgetDays] = useState(300);
  const [expandedAction, setExpandedAction] = useState(null);
  const [showAll, setShowAll] = useState(false);

  const portfolio = useMemo(() => aggregateRisk(computeRiskFromPerformance(DATA, {})), []);

  const allActions = useMemo(() => {
    const raw = generateActions({});
    return addCumulativeReduction(raw);
  }, []);

  const withinBudget = useMemo(() => {
    let totalEffort = 0;
    return allActions.filter(a => {
      if (totalEffort + a.effort > budgetDays) return false;
      totalEffort += a.effort;
      return true;
    });
  }, [allActions, budgetDays]);

  const totalReduction = withinBudget.length > 0
    ? withinBudget[withinBudget.length - 1].cumulativeReduction
    : 0;
  const totalEffort = withinBudget.reduce((a, x) => a + x.effort, 0);

  const displayActions = showAll ? allActions : allActions.slice(0, 20);
  const maxEfficiency = allActions.length > 0 ? allActions[0].efficiency : 1;

  // Simple SVG cumulative curve
  const curveW = 700, curveH = 180, padL = 60, padR = 30, padT = 20, padB = 40;
  const plotW = curveW - padL - padR, plotH = curveH - padT - padB;
  const maxEffort = allActions.length > 0 ? allActions[allActions.length - 1].cumulativeEffort : 1;
  const maxReduction = allActions.length > 0 ? allActions[allActions.length - 1].cumulativeReduction : 1;
  const scaleX = (e) => padL + (e / maxEffort) * plotW;
  const scaleY = (r) => padT + plotH - (r / maxReduction) * plotH;

  const curvePath = useMemo(() => {
    if (allActions.length === 0) return '';
    const points = allActions.map(a => `${scaleX(a.cumulativeEffort).toFixed(1)},${scaleY(a.cumulativeReduction).toFixed(1)}`);
    return `M${padL},${padT + plotH} L${points.join(' L')}`;
  }, [allActions]);

  return (
    <div style={{ maxWidth: 900, margin: '0 auto' }}>
      <ScreenHeader
        title="Prioritized Action Queue"
        subtitle="What to do first with existing resources — ranked by risk reduction per unit of effort. Each action is structurally derived from the performance model."
        help="Actions are generated by identifying every dimension×phase cell where improvement is possible, computing the risk reduction that improvement would produce (via the what-if propagation chain), and dividing by estimated effort. The highest-leverage actions float to the top. The cumulative curve shows diminishing returns — after the top actions, each additional action buys less reduction per effort day."
      />

      {/* Summary strip */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: 12, marginBottom: 16 }}>
        {[
          { label: 'Current exposure', value: fmt.dollars(portfolio.rALE), color: 'var(--coral)' },
          { label: 'Reduction available', value: fmt.dollars(totalReduction), sub: `within ${budgetDays}-day budget`, color: 'var(--teal)' },
          { label: 'Actions in budget', value: `${withinBudget.length} of ${allActions.length}`, color: 'var(--navy)' },
          { label: 'Total effort', value: `${totalEffort} days`, sub: `of ${budgetDays}-day budget`, color: 'var(--text)' },
        ].map(s => (
          <div key={s.label} style={{
            background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 3,
            padding: '10px 14px', fontFamily: 'var(--mono)',
          }}>
            <div style={{ fontSize: 9, color: 'var(--text-muted)', letterSpacing: '1px', textTransform: 'uppercase', marginBottom: 2 }}>{s.label}</div>
            <div style={{ fontSize: 18, fontWeight: 700, color: s.color }}>{s.value}</div>
            {s.sub && <div style={{ fontSize: 9, color: 'var(--text-muted)' }}>{s.sub}</div>}
          </div>
        ))}
      </div>

      {/* Budget slider */}
      <div style={{
        background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 3,
        padding: '10px 16px', marginBottom: 16, fontFamily: 'var(--mono)',
        display: 'flex', alignItems: 'center', gap: 14,
      }}>
        <span style={{ fontSize: 9, letterSpacing: '1px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: 600 }}>
          Effort budget
        </span>
        <input type="range" min={50} max={1000} step={25} value={budgetDays}
          onChange={e => setBudgetDays(Number(e.target.value))}
          style={{ flex: 1 }} />
        <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--navy)', minWidth: 70 }}>
          {budgetDays} days
        </span>
        <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>
          ≈ {(budgetDays / 20).toFixed(1)} person-months
        </span>
      </div>

      {/* Cumulative reduction curve */}
      <div className="card" style={{ marginBottom: 16 }}>
        <div className="card-header">
          <span className="card-header-title">Cumulative risk reduction — diminishing returns curve</span>
          <span className="card-header-meta">
            {withinBudget.length > 0
              ? `First ${Math.min(5, withinBudget.length)} actions deliver ${portfolio.rALE > 0 ? ((withinBudget.slice(0, 5).reduce((a, x) => a + x.riskReduction, 0) / totalReduction) * 100).toFixed(0) : 0}% of total available reduction`
              : 'Adjust budget to see actions'}
          </span>
        </div>
        <div style={{ padding: '8px 12px' }}>
          <svg viewBox={`0 0 ${curveW} ${curveH}`} width="100%" style={{ display: 'block' }}>
            {/* Grid lines */}
            {[0.25, 0.5, 0.75].map(pct => (
              <line key={pct} x1={padL} y1={padT + plotH * (1 - pct)} x2={curveW - padR} y2={padT + plotH * (1 - pct)}
                stroke="var(--border)" strokeWidth="0.5" opacity="0.3" />
            ))}
            {/* Axes */}
            <line x1={padL} y1={padT + plotH} x2={curveW - padR} y2={padT + plotH} stroke="var(--text)" strokeWidth="0.5" opacity="0.4" />
            <line x1={padL} y1={padT} x2={padL} y2={padT + plotH} stroke="var(--text)" strokeWidth="0.5" opacity="0.4" />
            {/* Labels */}
            <text x={(padL + curveW - padR) / 2} y={curveH - 4} textAnchor="middle" fontSize="10" fontFamily="var(--mono)" fill="var(--text-muted)">
              Cumulative effort (person-days)
            </text>
            <text x={8} y={(padT + padT + plotH) / 2} textAnchor="middle" fontSize="10" fontFamily="var(--mono)" fill="var(--text-muted)"
              transform={`rotate(-90, 8, ${(padT + padT + plotH) / 2})`}>
              Risk reduction ($M)
            </text>
            {/* Y ticks */}
            {[0, 0.5, 1].map(pct => (
              <text key={`y-${pct}`} x={padL - 6} y={padT + plotH * (1 - pct) + 4} textAnchor="end" fontSize="9" fontFamily="var(--mono)" fill="var(--text-muted)">
                {fmt.dollars(maxReduction * pct)}
              </text>
            ))}
            {/* X ticks */}
            {[0, 0.25, 0.5, 0.75, 1].map(pct => (
              <text key={`x-${pct}`} x={padL + plotW * pct} y={padT + plotH + 16} textAnchor="middle" fontSize="9" fontFamily="var(--mono)" fill="var(--text-muted)">
                {Math.round(maxEffort * pct)}
              </text>
            ))}
            {/* Budget line */}
            {budgetDays <= maxEffort && (
              <>
                <line x1={scaleX(budgetDays)} y1={padT} x2={scaleX(budgetDays)} y2={padT + plotH}
                  stroke="var(--navy)" strokeWidth="1.5" strokeDasharray="4 3" opacity="0.5" />
                <text x={scaleX(budgetDays)} y={padT - 4} textAnchor="middle" fontSize="9" fontFamily="var(--mono)" fill="var(--navy)" fontWeight="600">
                  Budget: {budgetDays}d
                </text>
              </>
            )}
            {/* Curve */}
            {curvePath && <path d={curvePath} fill="none" stroke="var(--teal)" strokeWidth="2" />}
            {/* Area under curve within budget */}
            {withinBudget.length > 0 && (() => {
              const lastInBudget = withinBudget[withinBudget.length - 1];
              const budgetPoints = withinBudget.map(a => `${scaleX(a.cumulativeEffort).toFixed(1)},${scaleY(a.cumulativeReduction).toFixed(1)}`);
              const areaPath = `M${padL},${padT + plotH} L${budgetPoints.join(' L')} L${scaleX(lastInBudget.cumulativeEffort).toFixed(1)},${padT + plotH} Z`;
              return <path d={areaPath} fill="var(--teal)" opacity="0.1" />;
            })()}
            {/* Dots for top actions */}
            {allActions.slice(0, 10).map((a, i) => (
              <circle key={a.id} cx={scaleX(a.cumulativeEffort)} cy={scaleY(a.cumulativeReduction)} r={3}
                fill={a.cumulativeEffort <= budgetDays ? 'var(--teal)' : 'var(--text-dim)'} opacity="0.7" />
            ))}
          </svg>
        </div>
      </div>

      {/* Action list */}
      <div className="card" style={{ marginBottom: 16 }}>
        <div className="card-header">
          <span className="card-header-title">Ranked actions — highest leverage first</span>
          <span className="card-header-meta">
            {allActions.length} candidate actions · simulated effort estimates
          </span>
        </div>
        <div style={{ padding: 0 }}>
          {displayActions.map((a, i) => {
            const inBudget = withinBudget.some(w => w.id === a.id);
            const isExpanded = expandedAction === a.id;
            const stageColor = STAGE_COLORS[a.stage] || STAGE_COLORS["Initial Access"];
            const effBar = maxEfficiency > 0 ? (a.efficiency / maxEfficiency) * 100 : 0;

            return (
              <div key={a.id}
                onClick={() => setExpandedAction(isExpanded ? null : a.id)}
                style={{
                  borderBottom: '1px solid var(--border-light)',
                  background: inBudget ? 'transparent' : 'var(--bg-surface)',
                  opacity: inBudget ? 1 : 0.6,
                  cursor: 'pointer', transition: 'background 0.1s',
                }}
                onMouseOver={e => { if (inBudget) e.currentTarget.style.background = 'var(--bg-surface)'; }}
                onMouseOut={e => { if (inBudget) e.currentTarget.style.background = 'transparent'; }}
              >
                {/* Main row */}
                <div style={{
                  display: 'grid', gridTemplateColumns: '32px 1fr 100px 80px 80px 90px',
                  padding: '10px 14px', alignItems: 'center', fontFamily: 'var(--mono)',
                }}>
                  <span style={{ fontSize: 13, fontWeight: 700, color: inBudget ? 'var(--navy)' : 'var(--text-dim)' }}>
                    {a.rank}
                  </span>
                  <div>
                    <div style={{ fontSize: 11, fontWeight: 600 }}>
                      {a.description}
                    </div>
                    <div style={{ fontSize: 9, color: 'var(--text-muted)', display: 'flex', gap: 8, marginTop: 2 }}>
                      <span style={{
                        padding: '1px 5px', borderRadius: 2,
                        background: stageColor.bg, color: stageColor.text, fontWeight: 600,
                      }}>{ATTACK.stages[a.stage]?.label || a.stage}</span>
                      <span>{a.affectedScenarioCount} scenarios</span>
                      <span>{a.currentValue}% → {a.targetValue}%</span>
                    </div>
                  </div>
                  {/* Efficiency bar */}
                  <div>
                    <div style={{ height: 6, background: 'var(--bg-surface)', borderRadius: 3, overflow: 'hidden', marginBottom: 2 }}>
                      <div style={{ height: '100%', width: `${effBar}%`, background: 'var(--teal)', opacity: 0.5, borderRadius: 3 }} />
                    </div>
                    <div style={{ fontSize: 8, color: 'var(--text-muted)', textAlign: 'center' }}>efficiency</div>
                  </div>
                  <div style={{ textAlign: 'right', fontSize: 12, fontWeight: 700, color: 'var(--teal)' }}>
                    {fmt.dollars(a.riskReduction)}
                  </div>
                  <div style={{ textAlign: 'right', fontSize: 11, color: 'var(--text-muted)' }}>
                    {a.effort} days
                  </div>
                  <div style={{ textAlign: 'right', fontSize: 10, color: 'var(--text-muted)' }}>
                    {fmt.dollars(a.cumulativeReduction)} total
                  </div>
                </div>

                {/* Expanded detail */}
                {isExpanded && (
                  <div style={{
                    padding: '8px 14px 14px 46px', background: 'var(--bg-surface)',
                    fontFamily: 'var(--mono)', fontSize: 10, lineHeight: 1.7,
                    borderTop: '1px solid var(--border-light)',
                  }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                      <div>
                        <div style={{ fontWeight: 700, fontSize: 9, letterSpacing: '1px', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 4 }}>
                          What this action means
                        </div>
                        <div style={{ color: 'var(--text)' }}>
                          Improve <strong>{a.dimLabel}</strong> performance at the <strong>{a.phaseLabel}</strong> phase
                          for the <strong>{a.objectiveName}</strong> control objective.
                          This raises the performance cell from {a.currentValue}% to {a.targetValue}% (max achievable: {a.maxValue}%).
                        </div>
                        <div style={{ marginTop: 8 }}>
                          <strong>Affected scenarios:</strong> {a.affectedScenarios.join(', ')}
                        </div>
                      </div>
                      <div>
                        <div style={{ fontWeight: 700, fontSize: 9, letterSpacing: '1px', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 4 }}>
                          Impact analysis
                        </div>
                        <div>Risk reduction: <strong style={{ color: 'var(--teal)' }}>{fmt.dollars(a.riskReduction)}</strong> per year</div>
                        <div>Effort estimate: <strong>{a.effort} person-days</strong> (~{(a.effort / 20).toFixed(1)} person-months)</div>
                        <div>Efficiency: <strong>{(a.riskReduction / a.effort * 1000).toFixed(0)}</strong> $K reduction per person-day</div>
                        <div style={{ marginTop: 8 }}>
                          <button className="btn" style={{ fontSize: 9 }}
                            onClick={(e) => { e.stopPropagation(); onNavigate('performance'); }}>
                            View in Performance grid →
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {!showAll && allActions.length > 20 && (
        <div style={{ textAlign: 'center', marginBottom: 16 }}>
          <button className="btn" onClick={() => setShowAll(true)} style={{ fontSize: 10 }}>
            Show all {allActions.length} actions
          </button>
        </div>
      )}

      {/* Escalation to Type #3 */}
      <div className="callout bg-amber" style={{ marginBottom: 16 }}>
        <div className="callout-title">When existing resources aren't enough</div>
        <div style={{ fontFamily: 'var(--mono)', fontSize: 11, lineHeight: 1.7 }}>
          If the actions within your effort budget don't reduce risk below tolerance, the next question is:
          what new investment would close the gap?
          <div style={{ marginTop: 8 }}>
            <button className="btn btn-active" style={{ fontSize: 10, padding: '6px 14px', background: '#D85A30', borderColor: '#D85A30' }}
              onClick={() => onNavigate('invest')}>
              → Evaluate new investment options (Type #3)
            </button>
          </div>
        </div>
      </div>

      {/* Data note */}
      <div style={{
        fontFamily: 'var(--mono)', fontSize: 9, color: 'var(--text-dim)',
        fontStyle: 'italic', lineHeight: 1.6, textAlign: 'center',
      }}>
        Effort estimates are simulated (person-days per 10-point improvement, scaled by dimension and phase difficulty).
        Risk reduction is computed from the performance model's what-if propagation chain.
        <br />In production, effort estimates would come from organizational capacity assessments.
      </div>

      <Legend items={[
        { color: 'var(--teal)', label: 'Within effort budget' },
        { color: 'var(--bg-surface)', label: 'Outside budget (lower priority)' },
        { color: 'var(--navy)', label: 'Budget line on cumulative curve' },
      ]} />
    </div>
  );
}
